# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ed9OAkItApJQn0s-gJEZc21N0rZUD4FV
"""

import pandas as pd
data=pd.read_csv('/content/Iris.csv')

data.head(10)

from sklearn.model_selection import train_test_split

features=data.drop('Species',axis=1)
target=data[['Species']]

x_train,x_test,y_train,y_test=train_test_split(features,target,train_size=0.8,random_state=10)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

prediction=model.fit(x_train,y_train).predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,prediction)